/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      screens: {
        xs: "480px",
        desktop: "1200px",
      },
      colors: {
        primary: "#1A1A1A",
        "primary-dark": "#F2EDE3",
        "on-primary": "#FFFFFF",
        "on-primary-dark": "#1A1A1A",
        secondary: "#2E2A24",
        "secondary-dark": "#3A342B",
        "secondary-light": "#EFE8DA",
        "secondary-light-dark": "#332E26",
        "on-secondary": "#FFFFFF",
        "on-secondary-dark": "#F2EDE3",
        "on-secondary-light": "#2E2A24",
        "on-secondary-light-dark": "#F2EDE3",
        accent: "#8A5A2B",
        "accent-dark": "#D9B98A",
        "on-accent": "#FFFFFF",
        "on-accent-dark": "#1A1A1A",
        "accent-soft": "#C4A77D",
        "accent-soft-dark": "#8A6A43",
        background: "#FAFAF8",
        "background-dark": "#17150F",
        foreground: "#1A1A1A",
        "foreground-dark": "#F2EDE3",
        card: "#FFFEFA",
        "card-dark": "#211E18",
        "card-foreground": "#1A1A1A",
        "card-foreground-dark": "#F2EDE3",
        muted: "#F1EDE4",
        "muted-dark": "#2B2720",
        "muted-foreground": "#4A4A4A",
        "muted-foreground-dark": "#B8AF9F",
        border: "#D6CEBE",
        "border-dark": "#3E382E",
        destructive: "#B42318",
        "destructive-dark": "#F97066",
        "on-destructive": "#FFFFFF",
        "on-destructive-dark": "#1A1A1A",
        ring: "#1A1A1A",
        "ring-dark": "#F2EDE3",
      },
      borderRadius: {
        none: "0px",
        sm: "8px",
        md: "12px",
        lg: "18px",
        xl: "26px",
        full: "9999px",
      },
      spacing: {
        xxs: "4px",
        xs: "8px",
        sm: "12px",
        md: "17px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        section: "80px",
      },
      fontFamily: {
        sans: ["Cabin", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        display: ["Newsreader", "Georgia", "serif"],
      },
      fontSize: {
        "hero-display": ["56px", { lineHeight: "1.07", letterSpacing: "-0.28px", fontWeight: "600" }],
        "display-lg": ["40px", { lineHeight: "1.10", letterSpacing: "0", fontWeight: "600" }],
        "display-md": ["34px", { lineHeight: "1.47", letterSpacing: "-0.374px", fontWeight: "600" }],
        lead: ["28px", { lineHeight: "1.14", letterSpacing: "0.196px", fontWeight: "400" }],
        "lead-airy": ["24px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "300" }],
        tagline: ["21px", { lineHeight: "1.19", letterSpacing: "0.231px", fontWeight: "600" }],
        "body-strong": ["17px", { lineHeight: "1.24", letterSpacing: "-0.374px", fontWeight: "600" }],
        body: ["17px", { lineHeight: "1.47", letterSpacing: "-0.374px", fontWeight: "400" }],
        "dense-link": ["17px", { lineHeight: "2.41", letterSpacing: "0", fontWeight: "400" }],
        caption: ["14px", { lineHeight: "1.43", letterSpacing: "-0.224px", fontWeight: "400" }],
        "caption-strong": ["14px", { lineHeight: "1.29", letterSpacing: "-0.224px", fontWeight: "600" }],
        "button-large": ["18px", { lineHeight: "1.0", letterSpacing: "0", fontWeight: "500" }],
        "button-utility": ["14px", { lineHeight: "1.29", letterSpacing: "-0.224px", fontWeight: "400" }],
        "fine-print": ["12px", { lineHeight: "1.0", letterSpacing: "-0.12px", fontWeight: "400" }],
        "micro-legal": ["10px", { lineHeight: "1.3", letterSpacing: "-0.08px", fontWeight: "400" }],
        "nav-link": ["12px", { lineHeight: "1.0", letterSpacing: "-0.12px", fontWeight: "400" }],
      },
      boxShadow: {
        // Back-compat alias: un-migrated `shadow-glow-accent` usages render as an ink offset.
        "glow-accent": "2px 2px 0 #1A1A1A",
        ink: "3px 3px 0 #1A1A1A",
        "ink-sm": "2px 2px 0 #1A1A1A",
        "ink-dark": "3px 3px 0 #000000",
        "ink-sm-dark": "2px 2px 0 #000000",
        "glow-ring": "0 0 0 3px rgba(26,26,26,0.18)",
        "glow-ring-dark": "0 0 0 3px rgba(242,237,227,0.22)",
      },
    },
  },
  plugins: [
    function ({ addUtilities }) {
      addUtilities({
        // Back-compat no-op: glow text is not part of Paper Studio.
        ".text-glow": { textShadow: "none" },
        ".paper-grain": {
          backgroundImage:
            "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='160' height='160'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='2' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.05'/%3E%3C/svg%3E\")",
          backgroundRepeat: "repeat",
        },
      });
    },
  ],
};
