/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      screens: {
        xs: "480px",
        desktop: "1200px",
      },
      colors: {
        primary: "#0F0F23",
        "on-primary": "#FFFFFF",
        secondary: "#1E1B4B",
        "secondary-light": "#EEF2FF",
        "on-secondary": "#FFFFFF",
        "on-secondary-light": "#1E1B4B",
        accent: "#E11D48",
        "on-accent": "#FFFFFF",
        background: "#FBF7F2",
        "background-dark": "#000000",
        foreground: "#0F0F23",
        "foreground-dark": "#F8FAFC",
        card: "#FFFFFF",
        "card-dark": "#0C0C0D",
        "card-foreground": "#0F0F23",
        "card-foreground-dark": "#F8FAFC",
        muted: "#F5F0E8",
        "muted-dark": "#181818",
        "muted-foreground": "#6B6155",
        "muted-foreground-dark": "#94A3B8",
        border: "#E2E8F0",
        "border-dark": "#312E81",
        destructive: "#DC2626",
        "destructive-dark": "#EF4444",
        "on-destructive": "#FFFFFF",
        "on-destructive-dark": "#000000",
        ring: "#0F0F23",
        "ring-dark": "#FFFFFF",
      },
      borderRadius: {
        none: "0px",
        sm: "6px",
        md: "10px",
        lg: "14px",
        xl: "20px",
        full: "9999px",
      },
      spacing: {
        xxs: "4px",
        xs: "8px",
        sm: "12px",
        md: "17px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        section: "80px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
      },
      fontSize: {
        "hero-display": ["56px", { lineHeight: "1.07", letterSpacing: "-0.28px", fontWeight: "600" }],
        "display-lg": ["40px", { lineHeight: "1.10", letterSpacing: "0", fontWeight: "600" }],
        "display-md": ["34px", { lineHeight: "1.47", letterSpacing: "-0.374px", fontWeight: "600" }],
        lead: ["28px", { lineHeight: "1.14", letterSpacing: "0.196px", fontWeight: "400" }],
        "lead-airy": ["24px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "300" }],
        tagline: ["21px", { lineHeight: "1.19", letterSpacing: "0.231px", fontWeight: "600" }],
        "body-strong": ["17px", { lineHeight: "1.24", letterSpacing: "-0.374px", fontWeight: "600" }],
        body: ["17px", { lineHeight: "1.47", letterSpacing: "-0.374px", fontWeight: "400" }],
        "dense-link": ["17px", { lineHeight: "2.41", letterSpacing: "0", fontWeight: "400" }],
        caption: ["14px", { lineHeight: "1.43", letterSpacing: "-0.224px", fontWeight: "400" }],
        "caption-strong": ["14px", { lineHeight: "1.29", letterSpacing: "-0.224px", fontWeight: "600" }],
        "button-large": ["18px", { lineHeight: "1.0", letterSpacing: "0", fontWeight: "500" }],
        "button-utility": ["14px", { lineHeight: "1.29", letterSpacing: "-0.224px", fontWeight: "400" }],
        "fine-print": ["12px", { lineHeight: "1.0", letterSpacing: "-0.12px", fontWeight: "400" }],
        "micro-legal": ["10px", { lineHeight: "1.3", letterSpacing: "-0.08px", fontWeight: "400" }],
        "nav-link": ["12px", { lineHeight: "1.0", letterSpacing: "-0.12px", fontWeight: "400" }],
      },
      boxShadow: {
        "glow-accent": "0 0 12px rgba(225,29,72,0.45)",
        "glow-ring": "0 0 0 3px rgba(15,15,35,0.12)",
        "glow-ring-dark": "0 0 0 3px rgba(255,255,255,0.15)",
      },
    },
  },
  plugins: [
    function ({ addUtilities }) {
      addUtilities({
        ".text-glow": { textShadow: "0 0 10px currentColor" },
      });
    },
  ],
};
